# -*- coding: utf-8 -*-
"""Teste Técnico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvEDWmTTWVFQAz-r7GcTA-IHLwFzqlcO
"""

#1  Observe o trecho de código abaixo: int INDICE = 13, SOMA = 0, K = 0;
# Enquanto K < INDICE faça { K = K + 1; SOMA = SOMA + K; }
# Imprimir(SOMA);
# Ao final do processamento, qual será o valor da variável SOMA?
indice = 13
SOMA = 0
k = 0
while k < indice:
  k = k + 1
  SOMA = SOMA + k
print(SOMA)

#2 Dado a sequência de Fibonacci, onde se inicia por 0 e 1 e o próximo valor sempre será a soma dos 2 valores anteriores (exemplo: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34...),
# escreva um programa na linguagem que desejar onde, informado um número, ele calcule a sequência de Fibonacci e retorne uma mensagem avisando se o número informado pertence ou não a sequência.
user = int(input("Digite um número inteiro para verificar sua existência na sequência de Fibonacci: "))
fibonnachi = [0,1]
for i in range(0,user):
  soma = fibonnachi[-1] + fibonnachi[-2]
  fibonnachi.append(soma)
if user in fibonnachi:
  print(f'O número {user} está presente na sequência de fibonnachi.')
else:
  print(f'O número {user} não está presente na sequência')
print(fibonnachi)

#3 Dado um vetor que guarda o valor de faturamento diário de uma distribuidora, faça um programa, na linguagem que desejar, que calcule e retorne:
# O menor valor de faturamento ocorrido em um dia do mês;
# O maior valor de faturamento ocorrido em um dia do mês;
# Número de dias no mês em que o valor de faturamento diário foi superior à média mensal.

import json
with open('dados.json', 'r') as arquivo_json:
  dados = json.load(arquivo_json)

valores = []

for item in dados:
  if item["valor"] > 0:
    valores.append(item["valor"])

print(valores)
print(f'Menor valor: {min(valores)}')
print(f'Maior valor: {max(valores)}')
media = sum(valores) / len(valores)
print(f'A média é {media}')
print(dados)

#4 Dado o valor de faturamento mensal de uma distribuidora, detalhado por estado:
# SP – R$67.836,43
# RJ – R$36.678,66
# MG – R$29.229,88
# ES – R$27.165,48
# Outros – R$19.849,53
# Escreva um programa na linguagem que desejar onde calcule o percentual de representação que cada estado teve dentro do valor total mensal da distribuidora.

estados = [{'estado':'SP', 'valor':67.836}, {'estado':'RJ', 'valor':36.678}, {'estado':'MG', 'valor':29.229}, {'estado':'ES', 'valor':27.165},{'estado':'OUTROS','valor':19.849}
]
valores = []
total = sum(item['valor'] for item in estados)

for item in estados:
  valores.append(item["valor"])
  percentual = item["valor"]/total * 100
  percentual_arredondado = round(percentual,2)
  print(f'Estado {item["estado"]}: {item["valor"]} -- {percentual_arredondado}%')

#5 Escreva um programa que inverta os caracteres de um string.
word = str(input('Digite uma palavra para inverter: '))
print(word[::-1])